// <auto-generated />
// This code was generated by a tool (LocalizationGenerator.cs)
// Do not modify this file manually.

namespace Gameplay.UI.Localization
{
    public static class LocKeys
    {
        public const string SplashLoading = "splash_loading";
        public const string LoginGuest = "login_guest";
        public const string LoginStatusReady = "login_status_ready";
        public const string LoginStatusConnecting = "login_status_connecting";
        public const string LoginStatusConnected = "login_status_connected";
        public const string LoginStatusFailed = "login_status_failed";
        public const string LoginStatusError = "login_status_error";
        public const string LoadingStatusPreheating = "loading_status_preheating";
        public const string LoadingStatusChopping = "loading_status_chopping";
        public const string LoadingStatusSyncing = "loading_status_syncing";
        public const string LoadingTipTitle = "loading_tip_title";
        public const string LoadingTip1 = "loading_tip_1";
        public const string LoadingTip2 = "loading_tip_2";
        public const string LoadingTip3 = "loading_tip_3";
        public const string MatchmakingStatusSearching = "matchmaking_status_searching";
        public const string MatchmakingStatusFound = "matchmaking_status_found";
        public const string MatchmakingButtonCancel = "matchmaking_button_cancel";
        public const string MatchmakingStatusJoining = "matchmaking_status_joining";
        public const string SettingsTitle = "settings_title";
        public const string SettingsTabGeneral = "settings_tab_general";
        public const string SettingsTabGraphics = "settings_tab_graphics";
        public const string SettingsTabControls = "settings_tab_controls";
        public const string SettingsTabGameplay = "settings_tab_gameplay";
        public const string SettingsTabSupport = "settings_tab_support";
        public const string SettingsTabAccount = "settings_tab_account";
        public const string SettingsHeaderAudio = "settings_header_audio";
        public const string SettingsHeaderDisplay = "settings_header_display";
        public const string SettingsHeaderInput = "settings_header_input";
        public const string SettingsHeaderGame = "settings_header_game";
        public const string SettingsHeaderLegal = "settings_header_legal";
        public const string SettingsHeaderProfile = "settings_header_profile";
        public const string SettingsSectAudio = "settings_sect_audio";
        public const string SettingsSectDisplay = "settings_sect_display";
        public const string SettingsSectInput = "settings_sect_input";
        public const string SettingsSectOptions = "settings_sect_options";
        public const string SettingsSectInfo = "settings_sect_info";
        public const string SettingsSectSession = "settings_sect_session";
        public const string SettingsSectData = "settings_sect_data";
        public const string SettingsOptMusic = "settings_opt_music";
        public const string SettingsDescMusic = "settings_desc_music";
        public const string SettingsOptSfx = "settings_opt_sfx";
        public const string SettingsDescSfx = "settings_desc_sfx";
        public const string SettingsOptMute = "settings_opt_mute";
        public const string SettingsDescMute = "settings_desc_mute";
        public const string SettingsOptQuality = "settings_opt_quality";
        public const string SettingsDescQuality = "settings_desc_quality";
        public const string SettingsBtnEditJoystick = "settings_btn_edit_joystick";
        public const string SettingsBtnEdit = "settings_btn_edit";
        public const string SettingsOptVibration = "settings_opt_vibration";
        public const string SettingsDescVibration = "settings_desc_vibration";
        public const string SettingsOptLanguage = "settings_opt_language";
        public const string SettingsDescLanguage = "settings_desc_language";
        public const string SettingsOptNotifications = "settings_opt_notifications";
        public const string SettingsDescNotifications = "settings_desc_notifications";
        public const string SettingsBtnHelp = "settings_btn_help";
        public const string SettingsBtnSupport = "settings_btn_support";
        public const string SettingsBtnPrivacy = "settings_btn_privacy";
        public const string SettingsBtnTerms = "settings_btn_terms";
        public const string SettingsBtnCredits = "settings_btn_credits";
        public const string SettingsBtnParent = "settings_btn_parent";
        public const string SettingsOptLogout = "settings_opt_logout";
        public const string SettingsDescLogout = "settings_desc_logout";
        public const string SettingsBtnLogout = "settings_btn_logout";
        public const string SettingsBtnReset = "settings_btn_reset";
        public const string SettingsBtnClear = "settings_btn_clear";
        public const string SettingsBtnBack = "settings_btn_back";
        public const string SettingsTabLegal = "settings_tab_legal";
        public const string SettingsSectConnections = "settings_sect_connections";
        public const string SettingsSectSupport = "settings_sect_support";
        public const string SettingsStatusConnected = "settings_status_connected";
        public const string SettingsBtnLink = "settings_btn_link";
        public const string SettingsBtnOpen = "settings_btn_open";
        public const string SettingsBtnChat = "settings_btn_chat";
        public const string SettingsOptHelpCenter = "settings_opt_help_center";
        public const string SettingsDescHelpCenter = "settings_desc_help_center";
        public const string SettingsOptSupport = "settings_opt_support";
        public const string SettingsDescSupport = "settings_desc_support";
        public const string SettingsOptGooglePlay = "settings_opt_google_play";
        public const string SettingsDescGooglePlay = "settings_desc_google_play";
        public const string SettingsOptFacebook = "settings_opt_facebook";
        public const string SettingsDescFacebook = "settings_desc_facebook";
        public const string LobbyPlayButton = "lobby_play_button";
        public const string LobbyRegionNa = "lobby_region_na";
        public const string LobbyInvite = "lobby_invite";
        public const string MainTabPlay = "main_tab_play";
        public const string MainTabCompete = "main_tab_compete";
        public const string MainTabShop = "main_tab_shop";
        public const string LobbyGameMode = "lobby_game_mode";
        public const string LobbyRegionPrefix = "lobby_region_prefix";
        public const string MainMenuLvlPrefix = "main_menu_lvl_prefix";
        public const string MainMenuRankVanguard = "main_menu_rank_vanguard";
        public const string MainMenuRankBronzeI = "main_menu_rank_bronze_i";
        public const string SettingsWarningGuest = "settings_warning_guest";
        public const string GuestLoginLabel = "guest_login_label";
    }
}
